codestates/underTheSea

client/src/modalComponent/PwdChange1.js
client/src/modalComponent/SignOut.js
client/src/page/Mypage.js
client/src/page/MypageComment.js
client/src/page/MypageContent.js
client/src/page/MypageManage.js
client/src/page/MypageMenuBar.js

[Client] / #12 / Add: Mypage.js media query

---

client/src/Manage2Component/ManagaDetail.js
client/src/component/ActivationCard.js
client/src/component/FilterMediaCard.js
client/src/component/Header.js
client/src/component/Header2.js
client/src/component/HowToManageCard.js
client/src/component/LymphoCard.js
client/src/component/RecommendCard.js
client/src/component/SkimmerCard.js
client/src/component/SuppliesCard.js
client/src/component/TipCard.js
client/src/component/WSDCard.js
client/src/component/WordCard.js
client/src/page/SeaWaterGuide.js

[Client] / #12 / Edit: manageDetail mediaQuery

---

client/src/page/Guide.js

dev -> dev
가이드 페이지 가로값 변경 (1920px)

[Client] / #12 / Fix: guidePage width

---

client/src/Landing_component/LandingGuide.js
client/src/Landing_component/LandingManage.js
client/src/Landing_component/LandingSearch.js
client/src/Landing_component/Landingpage.js
client/src/component/Header.js
client/src/page/Guide.js

dev -> dev
max-width 2000px 로 변경

[Client] / #12 / Fix: max-width

---

client/src/Manage2Component/ManagaDetail.js
client/src/modalComponent/AddContainer.js
client/src/page/Manage.js
client/src/page/ManageCard.js
client/src/page/ManageInfo.js

[Client] / #12 / Edit: manageMediaQuery

---

client/src/page/Mypage.js

[Client] / #12 / Edit: myPage max-width

---

scripts/start.sh
server/controllers/container/addfish.js
server/controllers/container/feed.js

[Server] / #8 / Edit : start.sh

---

client/src/Tips_component/WriteTips.js
server/controllers/container/addfish.js

[Client] / #12 / Fix: postMediaQuery

---

client/src/page/ManageInfo.js

[Client] / #12 / Edit: managePage

---

client/src/page/Mypage.js

dev -> dev
마이페이지 모바일 반응형 css 수정

[Client] / #12 / Edit: mypage mediaQuery

---

client/src/modalComponent/PwdChange1.js
client/src/modalComponent/SignOut.js

dev -> dev
마이페이지 모달창 높이값 px로 변경

[Client] / #12 / Edit: pwdchange

---

client/src/page/SeaWaterGuide.js

dev -> dev
해수어가이드 페이지 모바일 배너 보이게 수정

[Client] /#12 / Edit: seawaterGuide

---

client/src/page/Search.js
client/src/page/SearchCurrent.js
client/src/page/SearchInfo.js

[Client] / #12 / Searching : Media Edit

---

client/src/Manage2Component/ManagaDetail.js
client/src/modalComponent/PwdChange1.js
client/src/page/Search.js

[Client] / #12 / Fix

---

client/src/Landing_component/LandingManage1.js

[Client] / #12 / Edit : levelup

---

client/src/component/Header.js
client/src/component/Header2.js
client/src/modalComponent/Login.js

dev -> main
반응형헤더 CSS 자연스럽게 수정

[Client] /#12 / Fix: Header mediaQuery

---

client/src/Landing_component/LandingManage.js
client/src/Landing_component/LandingManage1.js
client/src/Landing_component/LandingSearch.js
client/src/component/Header.js
client/src/component/Header2.js

dev -> main
반응형헤더 280px로 수정 / 랜딩페이지 오른쪽 여백제거

[Client] / #12 / Fix: Header mediaQuery

---

client/src/Landing_component/Landingpage.js
client/src/component/Header.js
client/src/modalComponent/Login.js
client/src/modalComponent/SignUp.js

dev -> main
모바일환경에서 회원가입 모달창 CSS수정

[Client] / #12 / Edit: mobile signup

---

client/src/modalComponent/Login.js
client/src/page/Mypage.js

dev -> main
로그인 모달창 CSS 변경, 마이페이지 24인치 화면 버튼 텍스트크기 조정

[Client] / #12 / Edit: login, mypage btn text size

---

client/public/index.html
client/src/Manage2Component/ManagaDetail.js
client/src/modalComponent/Addfish.js
client/src/modalComponent/AquaInfo.js
client/src/modalComponent/Deadfish.js
client/src/modalComponent/ExChangeWaterInput.js
client/src/modalComponent/FeedingInput.js
client/src/modalComponent/HelpInfo.js

dev -> main
Manifest: Line: 1, column: 1, Syntax error 에러 해결
모바일환경 달력표기 에러 해결

[Client] / #12 / Fix: error

---

server/controllers/container/addfish.js
server/controllers/container/deletefish.js
server/controllers/container/feed.js
server/controllers/container/level.js
server/controllers/container/water.js
server/index.js

[Server] / #11 / Edit : CORS origin
